### ISSUE TITLE
Temporal extent does not follow the features specification

### ISSUE THREAD

**Issue by petergarnaes** [ngageoint/ogc-api-features-json-java#1]
The OpenAPI schema for OGC API Features clearly states that the temporal property should be an array, of array of datetime strings. [Link](http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/collection.yaml). Also see Requirement 17 or examples in the OGC API Features standard.

The [current implementation](https://github.com/ngageoint/ogc-api-features-json-java/blob/96ec7d9209e199ae03efe42295210b7633849ae3/src/main/java/mil/nga/oapi/features/json/Temporal.java#L16-L21) is only an array of strings.

**Comment by bosborn** [comment]
This was written off a draft version during a London OGC API Hackathon in 2019 before the temporal property was changed to an array of arrays.  It will have to be updated.  I have not tracked any spec changes since so let us know if there are any other things you notice.

**Comment by petergarnaes** [comment]
Thanks for the quick response. I will be sure to create other issues if I find them

**Comment by bosborn** [comment]
The Spatial bbox needed similar fix I made [here](https://github.com/ngageoint/ogc-api-features-json-java/commit/d21a93a54d462817081f1cc2df3d6615c27f5422).

**Comment by bosborn** [comment]
Released in [version 3.0.0](https://github.com/ngageoint/ogc-api-features-json-java/releases/tag/3.0.0)
